#!/usr/bin/env python3
"""
v60/gravity_recast/06_lorentz_commutant.py

C3 — from "plausible" toward "derived": WHERE can the soldering Lorentz so(3,1)
live, and is it automatically compatible with the internal G₂/color?

The soldering Lorentz must COMMUTE with the full internal symmetry Spin(7)
(= G₂ × SU(2)_L × SU(2)_R × U(1), the group v59 must keep unbroken for lepton=L,
Koide, gauge content).  Two questions, both computed (not asserted):

  (Q1, the no-go / DERIVATION)  What is the commutant of Spin(7) acting on the
      octonion 8 = V^8 inside End(ℝ⁸) = Cl(7)_even?  If it is trivial (scalars),
      then NO nontrivial so(3,1) (6-dim) can commute with the internal symmetry
      INSIDE the algebra v59 used for gravity (Λ²(V^8) = so(8) ⊂ End(V^8)).
      ⇒ the gravity carrier CANNOT be soldered internally; it is FORCED into a
        tensor extension.  This upgrades 04/05's "the carrier belongs in Cl(3,1)"
        from a suggestion to a consequence of Schur's lemma, and explains
        rigorously why the internal-soldering routes (01–03) were doomed.

  (Q2, the resolution / VERIFICATION)  In the tensor extension (spacetime module
      ⊗ octonion module), realize so(3,1) on the spacetime factor and color on
      the octonion factor.  Verify they commute exactly AND that the Lorentz acts
      trivially on the octonion factor (so G₂/color cannot see it — automatic
      compatibility).

Basis-independence note: Q1's commutant dimension is a representation-theoretic
invariant (Schur), independent of which octonion multiplication table is used; we
use a standard Cayley–Dickson table (same Spin(7) spinor rep as v59's Fano table).

Run:  python 06_lorentz_commutant.py
"""

import numpy as np

np.set_printoptions(precision=3, suppress=True)


# =============================================================================
# Octonions (Cayley–Dickson) and the Spin(7) spinor action on ℝ⁸
# =============================================================================

def quat_mult_table():
    # quaternion units 1,i,j,k as 4x4 left-mult? Build via explicit rule.
    # represent quaternion (a,b,c,d). We only need octonion CD below.
    pass


def octonion_mult(x, y):
    """Cayley–Dickson octonion product of two length-8 real vectors.
    O = H ⊕ H with (a,b)(c,d) = (ac - conj(d) b,  d a + b conj(c))."""
    def qconj(q):
        return np.array([q[0], -q[1], -q[2], -q[3]])

    def qmul(p, q):
        a1, b1, c1, d1 = p
        a2, b2, c2, d2 = q
        return np.array([
            a1*a2 - b1*b2 - c1*c2 - d1*d2,
            a1*b2 + b1*a2 + c1*d2 - d1*c2,
            a1*c2 - b1*d2 + c1*a2 + d1*b2,
            a1*d2 + b1*c2 - c1*b2 + d1*a2,
        ])
    a, b = x[:4], x[4:]
    c, d = y[:4], y[4:]
    left = qmul(a, c) - qmul(qconj(d), b)
    right = qmul(d, a) + qmul(b, qconj(c))
    return np.concatenate([left, right])


def left_mult_matrices():
    """8x8 left-multiplication matrices L_k (k=0..7); L_0 = I (real unit)."""
    e = [np.eye(8)[i] for i in range(8)]
    L = []
    for k in range(8):
        M = np.zeros((8, 8))
        for j in range(8):
            M[:, j] = octonion_mult(e[k], e[j])
        L.append(M)
    return L


def build_spin7_generators():
    """The 21 Spin(7) Lie-algebra generators on the octonion 8:
       products L_i L_j (1<=i<j<=7) of imaginary-unit left-multiplications.
       Each is antisymmetric; they span so(7) acting on the 8 spinor."""
    L = left_mult_matrices()
    # imaginary units are L[1..7]; verify they are antisymmetric, square to -I
    for k in range(1, 8):
        assert np.allclose(L[k] + L[k].T, 0), f"L_{k} not antisymmetric"
        assert np.allclose(L[k] @ L[k], -np.eye(8)), f"L_{k}^2 != -I"
    gens = []
    for i in range(1, 8):
        for j in range(i + 1, 8):
            G = L[i] @ L[j]
            gens.append(G)
    return gens, L


def commutant_dim(generators, n=8):
    """Dimension of {M in R^{n x n} : [M, G] = 0 for all G in generators}."""
    rows = []
    I = np.eye(n)
    for G in generators:
        # [M,G] = M G - G M ; vectorize M (n^2). Linear map: (G^T ⊗ I - I ⊗ G)
        K = np.kron(G.T, I) - np.kron(I, G)
        rows.append(K)
    A = np.vstack(rows)
    # nullspace dimension
    u, s, vh = np.linalg.svd(A)
    tol = 1e-9 * max(A.shape)
    rank = int(np.sum(s > tol))
    return n * n - rank


# =============================================================================
# Color su(3) ⊂ G₂ generators on the 8 (for comparison)
# =============================================================================

def color_su3_generators(L):
    """A color su(3) ⊂ G₂ realized inside so(7) generated by the L_iL_j.
    We do not need the exact v59 embedding for the commutant comparison; any
    su(3) ⊂ spin(7) gives the same branching 8 = 1⊕1⊕3⊕3̄.  For the tensor-
    extension demo (Q2) we only need *some* explicit internal generators that act
    on the octonion 8 — the Spin(7) generators themselves suffice."""
    g, _ = build_spin7_generators()
    return g  # use the full internal set for the strongest commutation demo


# =============================================================================
# so(3,1) on the 4-dim spacetime module (η = diag(-1,1,1,1))
# =============================================================================

def lorentz_generators():
    """6 generators of so(3,1) in the defining 4-vector rep.
    (M_{ab})^μ_ν = δ^μ_a η_{bν} − δ^μ_b η_{aν},  metric η = diag(-1,1,1,1)."""
    eta = np.diag([-1.0, 1, 1, 1])
    gens = {}
    pairs = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
    for (a, b) in pairs:
        M = np.zeros((4, 4))
        for mu in range(4):
            for nu in range(4):
                M[mu, nu] = (1 if mu == a else 0) * eta[b, nu] - (1 if mu == b else 0) * eta[a, nu]
        gens[(a, b)] = M
    return gens, eta


def check_lorentzian_signature(gens, eta):
    """so(3,1), not so(4), via convention-independent invariants:
       (a) every generator preserves the metric:  Mᵀ η + η M = 0;
       (b) boosts M_{0i} are NON-COMPACT (real eigenvalues ±1) while rotations
           M_{ij} are compact (imaginary eigenvalues ±i).  Non-compact generators
           exist  ⇔  the form is Lorentzian, not Euclidean so(4).
       (c) the boost commutator closes onto a rotation generator (the span)."""
    preserves = all(np.allclose(M.T @ eta + eta @ M, 0) for M in gens.values())
    K1 = gens[(0, 1)]
    J3 = gens[(1, 2)]
    boost_eigs = np.sort(np.real(np.linalg.eigvals(K1)))
    rot_eigs_im = np.sort(np.imag(np.linalg.eigvals(J3)))
    boost_noncompact = np.allclose(boost_eigs, [-1, 0, 0, 1])      # real ±1
    rot_compact = np.allclose(rot_eigs_im, [-1, 0, 0, 1])          # imaginary ±i
    K2 = gens[(0, 2)]
    comm = K1 @ K2 - K2 @ K1
    closes_on_rotation = np.allclose(comm, J3) or np.allclose(comm, -J3)
    return (preserves and boost_noncompact and rot_compact and closes_on_rotation,
            boost_eigs, rot_eigs_im)


# =============================================================================
# Main
# =============================================================================

def main():
    print("=" * 76)
    print("C3 — can a soldering Lorentz so(3,1) commute with internal Spin(7)?")
    print("=" * 76)

    spin7, L = build_spin7_generators()
    print(f"\nBuilt internal Spin(7): {len(spin7)} generators on the octonion 8.")
    # sanity: antisymmetric, independent count
    assert all(np.allclose(G + G.T, 0) for G in spin7), "Spin(7) gens not antisymmetric"
    # independent dimension of the span
    flat = np.array([G.flatten() for G in spin7])
    rank = np.linalg.matrix_rank(flat, tol=1e-9)
    print(f"  independent generators (dim of span) = {rank}  (so(7) = 21 expected)")

    # ---- Q1: commutant (the no-go / derivation) ----
    cdim = commutant_dim(spin7, n=8)
    print("\n" + "-" * 76)
    print("(Q1) Commutant of Spin(7) in End(ℝ⁸) = Cl(7)_even")
    print("-" * 76)
    print(f"  dim(commutant) = {cdim}")
    dim_so31 = 6
    if cdim == 1:
        print("  = 1  → ONLY scalar multiples of the identity commute with Spin(7).")
        print("        (Schur: the octonion 8 is an irreducible real Spin(7) module.)")
    print(f"  dim so(3,1) = {dim_so31}.  Since {cdim} < {dim_so31}, NO copy of so(3,1)")
    print("  can commute with the internal Spin(7) INSIDE End(ℝ⁸).")
    print("  ⇒ DERIVED: the gravity carrier cannot be soldered internally")
    print("     (v59 put Ω in Λ²(V⁸)=so(8) ⊂ End(V⁸) — forced scalar/no Lorentz room).")
    print("     The carrier MUST live in a tensor extension (the spacetime factor).")
    assert cdim == 1, f"expected trivial commutant (Schur), got {cdim}"

    # ---- so(3,1) exists and is Lorentzian ----
    lor, eta = lorentz_generators()
    ok_sig, boost_eigs, rot_eigs_im = check_lorentzian_signature(lor, eta)
    print("\n" + "-" * 76)
    print("so(3,1) on the 4-dim spacetime module")
    print("-" * 76)
    print(f"  boost M_01 eigenvalues (real)  = {boost_eigs}   → non-compact (±1)")
    print(f"  rot   M_12 eigenvalues (imag)  = {rot_eigs_im}   → compact (±i)")
    print(f"  preserves η, non-compact boosts present ⇒ Lorentzian so(3,1): {ok_sig}")
    assert ok_sig, "Lorentz signature check failed"
    # closure: all brackets stay in the 6-dim span
    span = np.array([M.flatten() for M in lor.values()])
    closed = True
    Ls = list(lor.values())
    for A in Ls:
        for B in Ls:
            c = (A @ B - B @ A).flatten()
            # is c in span?
            coeffs, res, *_ = np.linalg.lstsq(span.T, c, rcond=None)
            if np.linalg.norm(span.T @ coeffs - c) > 1e-9:
                closed = False
    print(f"  so(3,1) closes under commutator (6-dim Lie algebra): {closed}")
    assert closed

    # ---- Q2: tensor extension — the resolution / verification ----
    print("\n" + "-" * 76)
    print("(Q2) Tensor extension: spacetime(4) ⊗ octonion(8) = 32-dim")
    print("-" * 76)
    I8 = np.eye(8)
    I4 = np.eye(4)
    lor_ext = [np.kron(M, I8) for M in lor.values()]          # so(3,1) ⊗ Id
    int_ext = [np.kron(I4, G) for G in spin7]                 # Id ⊗ Spin(7)

    # commutation: every Lorentz generator commutes with every internal generator
    maxcomm = 0.0
    for A in lor_ext:
        for B in int_ext:
            maxcomm = max(maxcomm, np.max(np.abs(A @ B - B @ A)))
    print(f"  max |[so(3,1)⊗I , I⊗Spin(7)]| = {maxcomm:.2e}   (exact zero expected)")
    assert maxcomm < 1e-12

    # octonion-inertness: each Lorentz generator acts as identity on the octonion factor
    # i.e. it has the form M⊗I_8 — confirm by checking partial action on the 8-factor.
    inert = all(np.allclose(np.kron(M, I8), np.kron(M, I8)) for M in lor.values())
    # stronger: the Lorentz generators commute with ALL of End(octonion) lifted as I4⊗X
    test_X = [L[k] for k in range(8)] + [np.random.randn(8, 8)]
    maxX = 0.0
    for A in lor_ext:
        for X in test_X:
            B = np.kron(I4, X)
            maxX = max(maxX, np.max(np.abs(A @ B - B @ A)))
    print(f"  max |[so(3,1)⊗I , I⊗(any octonion-sector op)]| = {maxX:.2e}")
    print("  → the Lorentz acts trivially on the octonion factor: G₂/color CANNOT")
    print("    see it.  Compatibility is automatic (it touches a different factor).")
    assert maxX < 1e-9

    # ---- verdict ----
    print("\n" + "=" * 76)
    print("VERDICT on C3")
    print("=" * 76)
    print("""  DERIVED (Schur, basis-independent, verified):
    The internal Spin(7) is irreducible on the octonion 8, so its commutant in
    End(ℝ⁸)=Cl(7)_even is 1-dimensional (scalars).  A 6-dim Lorentz so(3,1)
    therefore CANNOT be soldered inside the algebra v59 used for gravity.  This
    forces the spin-2 carrier out of Λ²(V⁸) and into a tensor extension — exactly
    the spacetime (ℂ⊗ℍ / Cl(3,1)) factor identified in 04/05, and it explains
    rigorously why the internal-soldering routes 01–03 had to fail.

  VERIFIED (constructive):
    In the tensor extension, so(3,1) (on the spacetime factor) commutes with the
    full internal Spin(7) (on the octonion factor) and acts trivially on the
    octonion sector.  So the soldering is automatically G₂/triality/color-
    compatible — the worry that sank A2/B1 does not arise for the Cl(3,1) carrier.

  RESIDUAL (honest — a v59 gap, not a flaw here):
    That this tensor extension IS v59's single intended algebra ℂ⊗ℍ⊗𝕆, with a
    unique/forced embedding, is exactly the spacetime–internal integration that
    v59's own SevenDAlgebra header lists as 'a future refinement'.  Pinning that
    map closes C3 completely.  Until then: C3 is DERIVED modulo v59's unfinished
    merge — a substantial upgrade from 'plausible'.""")


if __name__ == "__main__":
    main()
