/*
 * sfa_field_mechanics.c
 *
 * Radial mechanical profile analyzer for SCP field configurations.
 * Reads SFA (voxel FRMD or cell-native FMSH/FCEL), computes radial profiles
 * of energy density, binding density |P|, and force-term imbalance (proxy for
 * local pressure / mechanical stress), then compares to the lattice reference
 * table generated by gen_proton_profiles.c.
 *
 * Designed for both the 6-field Cosserat braid (v55 L40) and v56 multivector
 * objects.
 *
 * Build (from v57/tools):
 *   gcc -O3 -fopenmp -I../../../sfa/format -o sfa_field_mechanics \
 *       sfa_field_mechanics.c -lzstd -lm
 *
 * The sfa.h single-header must have SFA_IMPLEMENTATION defined exactly once.
 *
 * Usage examples:
 *   ./sfa_field_mechanics /path/to/foam_L40_braid.sfa --ref ../data/proton_lattice_profiles.tsv
 *   ./sfa_field_mechanics v56_braid_rotor_L40.sfa --field-type multivector --r-max 2.0
 */

#define SFA_IMPLEMENTATION
#include "../../sfa/format/sfa.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <omp.h>
#include <float.h>
#include <assert.h>

/* ---------- Physics / defaults (6-field Cosserat) ---------- */
static double MU    = -41.345;
static double KAPPA = 50.0;
static double M2    = 2.25;      /* m² for phi */
static double ETA   = 0.5;

/* ---------- Binning ---------- */
#define MAX_R_BINS 512
static double R_MAX = 2.0;       /* fm — match the reference table */
static int    N_BINS = 201;

/* ---------- Reference table (loaded from TSV) ---------- */
typedef struct {
    double r;
    double eps_tot, p_tot;
    double eps_g,   p_g;
    double eps_q,   p_q;
} RefPoint;

static RefPoint *ref = NULL;
static int       n_ref = 0;

/* ============================================================
 * Load reference table (output of gen_proton_profiles)
 * ============================================================ */
static int load_reference(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) { perror("reference"); return 0; }

    char line[512];
    int count = 0;
    while (fgets(line, sizeof(line), f)) {
        if (line[0] == '#') continue;
        count++;
    }
    rewind(f);

    ref = calloc(count, sizeof(RefPoint));
    n_ref = 0;

    while (fgets(line, sizeof(line), f)) {
        if (line[0] == '#') continue;
        int n = sscanf(line, "%lf %lf %lf %*f %lf %lf %lf %lf",
                       &ref[n_ref].r,
                       &ref[n_ref].eps_tot, &ref[n_ref].p_tot,
                       &ref[n_ref].eps_g,   &ref[n_ref].p_g,
                       &ref[n_ref].eps_q,   &ref[n_ref].p_q);
        if (n >= 7) n_ref++;
    }
    fclose(f);
    fprintf(stderr, "Loaded %d reference points from %s\n", n_ref, path);
    return n_ref > 0;
}

/* ============================================================
 * Simple radial binning (for voxel grid or resampled cells)
 * ============================================================ */
typedef struct {
    double sum_mass;     /* |P| or energy */
    double sum_p;        /* pressure proxy */
    double sum_theta;
    double count;
} Bin;

static void bin_add(Bin *bins, double r, double val_mass, double val_p, double val_theta)
{
    if (r > R_MAX) return;
    int i = (int)((r / R_MAX) * (N_BINS - 1));
    if (i < 0) i = 0; if (i >= N_BINS) i = N_BINS-1;
    bins[i].sum_mass  += val_mass;
    bins[i].sum_p     += val_p;
    bins[i].sum_theta += val_theta;
    bins[i].count     += 1.0;
}

static void bin_finalize(Bin *bins)
{
    for (int i = 0; i < N_BINS; i++) {
        if (bins[i].count > 0) {
            bins[i].sum_mass  /= bins[i].count;
            bins[i].sum_p     /= bins[i].count;
            bins[i].sum_theta /= bins[i].count;
        }
    }
}

/* ============================================================
 * 6-field Cosserat force-term "pressure proxy"
 * In regions where the four terms do not perfectly cancel,
 * the residual is related to \partial^{2}phi/\partial t^{2} and
 * therefore to the effective mechanical pressure.
 * We use a simple scalar proxy: |Lapl + mass + V' + curl| averaged.
 * ============================================================ */
static inline double compute_force_imbalance_6field(
    double lap, double mass_term, double pot_deriv, double curl_term)
{
    return fabs(lap + mass_term + pot_deriv + curl_term);
}

/* ============================================================
 * Main analysis for 6-field (voxel or cell-resampled)
 * ============================================================ */
static void analyze_6field_voxel(SFA *sfa, int frame_idx, Bin *bins)
{
    /* For a real implementation we would:
     *   sfa_read_frame(...) to get phi[3], theta[3] or the 6 columns
     *   compute P = phi0*phi1*phi2 per voxel
     *   compute or read the four force terms per voxel (many runs already
     *   store diag per-voxel or we recompute Laplacian via finite differences)
     *
     * Since the exact L40 v55 cell-native SFA files are not currently
     * visible in the mounted volumes, this function is a stub that shows
     * the structure. When the data is available it drops in directly.
     */
    (void)sfa; (void)frame_idx; (void)bins;

    /* Placeholder: in a real run we would loop over all voxels,
     * compute r from centroid, bin the quantities.
     */
}

/* ============================================================
 * Comparison to reference
 * ============================================================ */
static void compare_to_reference(Bin *sim_bins, const char *label)
{
    if (!ref || n_ref == 0) return;

    double rms_p = 0, rms_eps = 0;
    int n = 0;

    for (int i = 0; i < n_ref; i++) {
        double r = ref[i].r;
        int bi = (int)((r / R_MAX) * (N_BINS - 1));
        if (bi < 0 || bi >= N_BINS || sim_bins[bi].count < 1) continue;

        /* Normalize both profiles to their max for shape comparison */
        double p_sim   = sim_bins[bi].sum_p;
        double p_ref   = ref[i].p_tot;
        double eps_sim = sim_bins[bi].sum_mass;   /* using |P| or E as proxy */
        double eps_ref = ref[i].eps_tot;

        rms_p   += (p_sim - p_ref) * (p_sim - p_ref);
        rms_eps += (eps_sim - eps_ref) * (eps_sim - eps_ref);
        n++;
    }
    if (n > 0) {
        rms_p   = sqrt(rms_p / n);
        rms_eps = sqrt(rms_eps / n);
        printf("%s  RMS_p=%.4f  RMS_eps=%.4f  (n=%d bins)\n", label, rms_p, rms_eps, n);
    }
}

/* ============================================================
 * Entry point
 * ============================================================ */
int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input.sfa> [--ref ref.tsv] [--r-max 2.0]\n", argv[0]);
        return 1;
    }

    const char *sfa_path = argv[1];
    const char *ref_path = NULL;

    for (int i = 2; i < argc; i++) {
        if (strcmp(argv[i], "--ref") == 0 && i+1 < argc) ref_path = argv[++i];
        if (strcmp(argv[i], "--r-max") == 0 && i+1 < argc) R_MAX = atof(argv[++i]);
    }

    if (ref_path) {
        if (!load_reference(ref_path)) {
            fprintf(stderr, "Warning: could not load reference — comparison disabled\n");
        }
    }

    /* Open SFA (works for both voxel and cell-native) */
    SFA sfa;
    if (sfa_open(&sfa, sfa_path) != SFA_OK) {
        fprintf(stderr, "Failed to open %s\n", sfa_path);
        return 1;
    }

    Bin *bins = calloc(N_BINS, sizeof(Bin));

    /* For now we demonstrate the pipeline on the first few frames.
     * A full version would loop over all frames with sfa_read_frame + proper
     * voxel or cell iteration.
     */
    int nframes = sfa.num_frames;
    fprintf(stderr, "SFA has %d frames. Analyzing first 3 as demonstration...\n", nframes);

    for (int f = 0; f < 3 && f < nframes; f++) {
        /* In real code: sfa_read_frame(&sfa, f, ...); then bin the fields */
        analyze_6field_voxel(&sfa, f, bins);
    }

    bin_finalize(bins);

    printf("# Radial mechanical profile (6-field Cosserat braid proxy)\n");
    printf("# r_fm   <P>     <force_imbalance>   <theta_rms>\n");
    for (int i = 0; i < N_BINS; i++) {
        double r = (i + 0.5) * R_MAX / N_BINS;
        printf("%.4f  %.6f  %.6f  %.6f\n",
               r,
               bins[i].sum_mass,
               bins[i].sum_p,
               bins[i].sum_theta);
    }

    if (ref) {
        compare_to_reference(bins, "v55_L40_braid");
    }

    free(bins);
    sfa_close(&sfa);
    free(ref);
    return 0;
}