#!/usr/bin/env python3
"""
v59/furey_construction/03_alpha_from_u1.py

Variant C: Derive U(1)_em coupling from algebra normalization.

With the SM idempotent identified in Variant B, we can attempt to compute
the natural U(1)_em coupling from the algebra alone, without external
normalization.

Approach 1: Coupling from the U(1) orbit volume.
  The U(1)_em group acts on the 8-dim Cl(6) rep space.  Its orbits
  are circles (1-dim) generically.  The "size" of the U(1) orbit
  relative to the full ambient space sets the coupling.

Approach 2: Coupling from the trace anomaly.
  The trace of Q^2 in a specific representation gives the coupling
  normalization.  Standard QED: 1/g_em^2 ∝ Tr(Q^2) in the chosen rep.

Approach 3: Coupling from the Casimir.
  For an SU(N) gauge group, g^2 ∝ 1/C_2(R) where C_2 is the second
  Casimir of the rep.  For U(1), C_2 ≡ Q^2 (per state).

We try all three approaches and see which gives a value near α ≈ 1/137.
"""

import numpy as np

print("="*72)
print("Variant C: U(1)_em coupling from Cl(6) ≅ C ⊗ O")
print("="*72)


# =========================================================================
# Set up Cl(6) and Witt basis (re-use code from Variant B)
# =========================================================================

sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I2 = np.eye(2, dtype=complex)

def tensor(*mats):
    result = mats[0]
    for m in mats[1:]:
        result = np.kron(result, m)
    return result

gamma = [
    tensor(sigma_x, I2, I2),
    tensor(sigma_y, I2, I2),
    tensor(sigma_z, sigma_x, I2),
    tensor(sigma_z, sigma_y, I2),
    tensor(sigma_z, sigma_z, sigma_x),
    tensor(sigma_z, sigma_z, sigma_y),
]

alpha = [(gamma[0] + 1j * gamma[1]) / 2,
         (gamma[2] + 1j * gamma[3]) / 2,
         (gamma[4] + 1j * gamma[5]) / 2]
alpha_bar = [(gamma[0] - 1j * gamma[1]) / 2,
             (gamma[2] - 1j * gamma[3]) / 2,
             (gamma[4] - 1j * gamma[5]) / 2]

N_op = sum(alpha_bar[i] @ alpha[i] for i in range(3))
# Number eigenvalues for our 8-dim rep
N_eigs = np.real(np.linalg.eigvals(N_op))

print(f"\nN eigenvalues (in 8-dim rep of Cl(6)): {sorted(N_eigs.round(3))}")
# Should be (0, 1, 1, 1, 2, 2, 2, 3)


# =========================================================================
# Approach 1: Coupling from U(1) orbit volume
# =========================================================================
print()
print("-"*72)
print("Approach 1: Coupling from U(1) orbit volume")
print("-"*72)

# U(1) generated by Q = -1/3 * (3 - 2N) = 2N/3 - 1 (or similar)
# Take charge operator Q = (1/3)(3 - 2N), giving charges (1, 1/3, -1/3, -1)

Q_op = (np.eye(8, dtype=complex) - (2.0/3.0) * N_op)
Q_eigs = np.real(np.linalg.eigvals(Q_op))
print(f"\nQ eigenvalues: {sorted(Q_eigs.round(4))}")

# Trace of Q^2 (the "Casimir" of U(1))
Tr_Q2 = np.trace(Q_op @ Q_op).real
print(f"Trace(Q^2) over 8-dim rep = {Tr_Q2:.4f}")

# In standard normalization, the U(1) coupling satisfies:
#   1/g^2 = Tr(Q^2) / (16 pi^2) for one generation in a specific normalization.
# Or equivalently: g^2 = 16 pi^2 / Tr(Q^2)
g_squared = 16 * np.pi**2 / Tr_Q2
alpha_pred = g_squared / (4 * np.pi)
print(f"\nPredicted g_em^2 = 16 pi^2 / Tr(Q^2) = {g_squared:.4f}")
print(f"Predicted alpha = g_em^2 / (4 pi) = {alpha_pred:.6f}")
print(f"Empirical alpha = 1/137.036 = {1/137.036:.6f}")
print(f"Ratio: {alpha_pred / (1/137.036):.4f}")


# =========================================================================
# Approach 2: Coupling from Casimir per representation
# =========================================================================
print()
print("-"*72)
print("Approach 2: Q^2 per representation")
print("-"*72)

# Compute Q^2 average over the 8 SM-like states
Q_eigvals_distinct, counts = np.unique(np.round(Q_eigs, 4), return_counts=True)
print(f"\nDistinct Q values and multiplicities:")
for q, c in zip(Q_eigvals_distinct, counts):
    print(f"  Q = {q:+.4f}: {c} states")

# Average Q^2:
Q2_avg = np.mean(Q_eigs**2)
print(f"\n<Q^2> = average over 8 states = {Q2_avg:.6f}")
print(f"alpha candidate = <Q^2>/(4 pi) = {Q2_avg/(4*np.pi):.6f}")
print(f"alpha candidate = 1/(4 pi <Q^2>) = {1/(4*np.pi*Q2_avg):.6f}")
print(f"Empirical: 1/137.036 = {1/137.036:.6f}")


# =========================================================================
# Approach 3: Generation-aware normalization
# =========================================================================
print()
print("-"*72)
print("Approach 3: Including all three generations")
print("-"*72)

# In the Standard Model, the U(1)_Y coupling g_1 is normalized such that
#   g_1^2 / (4 pi) at GUT scale = 3/5 * alpha_em / (cos^2 theta_W)
# For our purposes, the contribution of one generation to the U(1) beta
# function involves Tr(Q^2) summed over all states.

# Per generation:
Tr_Q2_per_gen = Tr_Q2
# Three generations:
Tr_Q2_total = 3 * Tr_Q2_per_gen
print(f"\nTr(Q^2) per generation = {Tr_Q2_per_gen:.4f}")
print(f"Tr(Q^2) over 3 generations = {Tr_Q2_total:.4f}")

# For an effective coupling:
alpha_3gen = 1 / Tr_Q2_total  # one possible normalization
print(f"\nalpha candidate = 1 / [Tr(Q^2) × 3 gens] = {alpha_3gen:.6f}")

# Test 137 -- what Tr(Q^2) would give alpha = 1/137?
# alpha = 1 / (some Tr(Q^2)) => Tr(Q^2) = 137
# Or alpha = Tr(Q^2) / (4 pi N) for some N
print(f"\nReverse engineering: what gives alpha^-1 = 137?")
target_alpha_inv = 137.036
# Candidates:
print(f"  If alpha = 1/x where x = some combination involving Tr(Q^2) and pi:")
print(f"    Tr(Q^2) × 4 pi = {Tr_Q2 * 4 * np.pi:.4f}")
print(f"    Tr(Q^2) × 4 pi^2 = {Tr_Q2 * 4 * np.pi**2:.4f}")
print(f"    Tr(Q^2) × 2 pi^2 = {Tr_Q2 * 2 * np.pi**2:.4f}")
print(f"    Tr(Q^2)^2 / 2 = {Tr_Q2**2 / 2:.4f}")
print(f"    Tr(Q^2) per-gen × 3 × 8 = {Tr_Q2 * 3 * 8:.4f}")
print(f"    Tr(Q^2) × 24 (= 3 gens × 8 states) = {Tr_Q2 * 24:.4f}")


# =========================================================================
# Approach 4: include Spin(7) factor of 21
# =========================================================================
print()
print("-"*72)
print("Approach 4: include dim Spin(7) = 21")
print("-"*72)

# From step 9, the cross-sector ratio 21 = dim Spin(7) appears naturally.
# Maybe alpha emerges as:
#   alpha = f(Tr(Q^2), dim Spin(7), other natural factors)

# Try: alpha = Tr(Q^2) / (4 pi × dim Spin(7))
alpha_with_spin7 = Tr_Q2 / (4 * np.pi * 21)
print(f"\nalpha = Tr(Q^2) / (4 pi × 21) = {alpha_with_spin7:.6f}")
print(f"alpha empirical                  = {1/137.036:.6f}")
print(f"ratio                            = {alpha_with_spin7 / (1/137.036):.4f}")

# Try: alpha = 1 / (4 pi × Tr(Q^2) × 21)
alpha_inv = 4 * np.pi * Tr_Q2 * 21
print(f"\n1/alpha = 4 pi × Tr(Q^2) × 21 = {alpha_inv:.4f}")
print(f"empirical 1/alpha             = {137.036:.4f}")
print(f"ratio                          = {alpha_inv / 137.036:.4f}")

# Try the Wyler-like combination
# Wyler: 137 ~ V(some) * something^(1/4)
# For our case:  21 (dim Spin(7)) × 2 pi^2 (V(S^3)) ~ ?
test_combos = [
    ("21 × 2 pi^2",              21 * 2 * np.pi**2),
    ("21 × pi",                  21 * np.pi),
    ("21 × pi / sqrt(2)",        21 * np.pi / np.sqrt(2)),
    ("8 pi × Tr(Q^2)",           8 * np.pi * Tr_Q2),
    ("Tr(Q^2) × 4 pi",            Tr_Q2 * 4 * np.pi),
    ("(2 pi^2) × Tr(Q^2)",       2 * np.pi**2 * Tr_Q2),
]
print()
print(f"{'expression':<30s} {'value':>12s} {'137 gap':>12s}")
for name, val in test_combos:
    print(f"  {name:<30s} {val:>12.4f} {val - 137.036:>+12.4f}")


# =========================================================================
# Summary
# =========================================================================
print()
print("="*72)
print("Summary")
print("="*72)
print(f"""
U(1)_em coupling from Cl(6) ≅ C ⊗ O:

Approach 1 (g^2 = 16 pi^2 / Tr(Q^2)):  alpha = {alpha_pred:.4f}
Approach 4 (1/alpha = 4 pi Tr(Q^2) × 21):  alpha^-1 = {alpha_inv:.4f}
Empirical: alpha = 1/137.036 = {1/137.036:.6f}, alpha^-1 = 137.036

NONE of the simple normalizations gives alpha = 1/137 cleanly.

The Tr(Q^2) for one SM generation = {Tr_Q2:.4f} = (4)(2/9) + ... (8/3 from the
8/3 = sum of charge squared for one generation in our convention).
This is a well-defined algebraic number, but its combination with pi
factors does not reproduce 137 in any obvious way.

Implication: alpha is NOT predicted by the Furey algebra alone in any
of the natural normalizations tested.  An additional input -- likely the
ratio of the gauge group orbit volume in the full algebra to a reference
volume -- is needed.  This is the Wyler-style geometric ratio that
remains unresolved.

What WAS achieved in this variant:
  - Confirmed Tr(Q^2) over one SM generation = {Tr_Q2:.4f} (an exact algebraic value).
  - Tested four natural normalizations for the U(1)_em coupling.
  - None reproduces empirical alpha at better than ~30% precision without tuning.

Variant C: PARTIAL (algebra confirmed, but alpha not predicted).
Proceed to Variant D for the instanton-action approach.
""")
