#!/usr/bin/env python3
"""Generate high-accuracy trig for cellfabi.

The original linear quarter-wave table (N=4096) accumulated enough phase
error that field unitary hops drifted rel_energy by ~1e-13..1e-8 and
failed the battery conservation bar (5e-14).

This generator emits a Cody–Waite style minimax polynomial for cos on
[0, π/4], with careful range reduction — double-quality for our use
(gate + field hops), without depending on a giant table. A small
reference table is still emitted for optional cross-checks / future
fixed-point work (ledger_lut=2).

Usage:
  python3 gen_trig_lut.py
  # writes trig_lut.inc
"""
import argparse
import math
import os

# fdlibm-ish coefficients for cos(x), x in [-pi/4, pi/4]
# cos(x) = 1 - x^2/2 + x^4 * (C1 + x^2*(C2+...))
# Using well-known double poly (SunPro/fdlibm C1..C6 style).
COS_POLY = [
    4.16666666666666019037e-02,   # C1  x^4
    -1.38888888888741095749e-03,  # C2
    2.48015872894767294178e-05,   # C3
    -2.75573143513906633035e-07,  # C4
    2.08757232129817482790e-09,   # C5
    -1.13596475577881948265e-11,  # C6
]

# sin(x) = x + x^3 * (S1 + x^2*(S2+...))
SIN_POLY = [
    -1.66666666666666324348e-01,  # S1
    8.33333333332248946124e-03,
    -1.98412698298579493134e-04,
    2.75573137070700676789e-06,
    -2.50507602534068634195e-08,
    1.58969099521155010221e-10,
]

REF_N = 4096  # small reference table only


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", default=os.path.join(os.path.dirname(__file__),
                                               "trig_lut.inc"))
    ap.add_argument("--ref-n", type=int, default=REF_N)
    a = ap.parse_args()
    n = a.ref_n

    lines = [
        "/* AUTO-GENERATED by gen_trig_lut.py — do not edit by hand */",
        "/* High-accuracy cos/sin via range reduction + minimax poly.",
        " * Optional reference quarter-wave table for ledger_lut=2. */",
        "",
        f"#define TRIG_LUT_N {n}",
        f"#define TRIG_PIO2 1.57079632679489661923",
        f"#define TRIG_PI   3.14159265358979323846",
        f"#define TRIG_PIX2 6.28318530717958647692",
        "",
        "/* cos poly coeffs C1..C6 for z=x*x: cos ~= 1 - 0.5z + z*z*(C1+z*(...)) */",
        "static const double TRIG_COS_C[6] = {",
    ]
    for i, c in enumerate(COS_POLY):
        comma = "," if i < len(COS_POLY) - 1 else ""
        lines.append(f"    {c:.17e}{comma}")
    lines.append("};")
    lines.append("static const double TRIG_SIN_S[6] = {")
    for i, c in enumerate(SIN_POLY):
        comma = "," if i < len(SIN_POLY) - 1 else ""
        lines.append(f"    {c:.17e}{comma}")
    lines.append("};")
    lines.append("")
    lines.append("/* reference table cos(k*pi/(2N)), k=0..N — optional path */")
    lines.append("static const double TRIG_COS_Q[TRIG_LUT_N + 1] = {")
    for k in range(n + 1):
        c = math.cos(k * math.pi / (2.0 * n))
        comma = "," if k < n else ""
        lines.append(f"    {c:.17e}{comma}")
    lines.append("};")
    lines.append("")

    # Inline C functions embedded in the .inc for single include
    lines.append(r"""
/* ---- high-accuracy cos/sin (default for cellfabi) ---- */
static double trig_kernel_cos(double x)
{
    /* x in [-pi/4, pi/4] */
    double z = x * x;
    double r = TRIG_COS_C[0] + z * (TRIG_COS_C[1] + z * (TRIG_COS_C[2]
              + z * (TRIG_COS_C[3] + z * (TRIG_COS_C[4] + z * TRIG_COS_C[5]))));
    return 1.0 - 0.5 * z + z * z * r;
}

static double trig_kernel_sin(double x)
{
    /* x in [-pi/4, pi/4] */
    double z = x * x;
    double v = z * x;
    double r = TRIG_SIN_S[0] + z * (TRIG_SIN_S[1] + z * (TRIG_SIN_S[2]
              + z * (TRIG_SIN_S[3] + z * (TRIG_SIN_S[4] + z * TRIG_SIN_S[5]))));
    return x + v * r;
}

static double lut_cos(double a)
{
    /* fold to [0, pi/2] then poly on [0, pi/4] via cos/sin kernels */
    double x = fmod(a, TRIG_PIX2);
    if (x < 0) x += TRIG_PIX2;
    int quad = (int)(x / TRIG_PIO2);
    double t = x - quad * TRIG_PIO2;
    double c, s;
    if (t <= TRIG_PIO2 * 0.5) {
        c = trig_kernel_cos(t);
        s = trig_kernel_sin(t);
    } else {
        double u = TRIG_PIO2 - t;
        c = trig_kernel_sin(u);
        s = trig_kernel_cos(u);
    }
    switch (quad & 3) {
    case 0: return c;
    case 1: return -s;
    case 2: return -c;
    default: return s;
    }
}

static double lut_sin(double a)
{
    return lut_cos(a - TRIG_PIO2);
}

/* optional coarse table path (ledger_lut=2) — linear quarter-wave */
static double lut_cos_table(double a)
{
    double x = fmod(a, TRIG_PIX2);
    if (x < 0) x += TRIG_PIX2;
    int quad = (int)(x / TRIG_PIO2);
    double t = x - quad * TRIG_PIO2;
    if (t <= 0) t = 0;
    if (t >= TRIG_PIO2) t = TRIG_PIO2;
    double xx = t * (2.0 * TRIG_LUT_N / TRIG_PI);
    if (xx < 0) xx = 0;
    if (xx > TRIG_LUT_N) xx = TRIG_LUT_N;
    int i = (int)xx;
    double f = xx - (double)i;
    double c, s;
    if (i >= TRIG_LUT_N) { c = TRIG_COS_Q[TRIG_LUT_N]; s = TRIG_COS_Q[0]; }
    else {
        c = TRIG_COS_Q[i] * (1.0 - f) + TRIG_COS_Q[i + 1] * f;
        double t2 = TRIG_PIO2 - t;
        double xx2 = t2 * (2.0 * TRIG_LUT_N / TRIG_PI);
        int j = (int)xx2;
        if (j >= TRIG_LUT_N) s = TRIG_COS_Q[TRIG_LUT_N];
        else {
            double f2 = xx2 - (double)j;
            s = TRIG_COS_Q[j] * (1.0 - f2) + TRIG_COS_Q[j + 1] * f2;
        }
    }
    switch (quad & 3) {
    case 0: return c;
    case 1: return -s;
    case 2: return -c;
    default: return s;
    }
}
""")

    out_path = a.o
    text = "\n".join(lines) + "\n"
    with open(out_path, "w") as f:
        f.write(text)

    # self-test accuracy
    import random
    maxe = 0.0
    # inject eval of poly via python mirror
    def kcos(x):
        z = x * x
        r = COS_POLY[0]
        for c in COS_POLY[1:]:
            r = r * z + c  # wrong order - match C horner from C0
        # C code: C0 + z*(C1+z*(C2+...))
        r = COS_POLY[0] + z * (COS_POLY[1] + z * (COS_POLY[2]
            + z * (COS_POLY[3] + z * (COS_POLY[4] + z * COS_POLY[5]))))
        return 1.0 - 0.5 * z + z * z * r

    def ksin(x):
        z = x * x
        r = SIN_POLY[0] + z * (SIN_POLY[1] + z * (SIN_POLY[2]
            + z * (SIN_POLY[3] + z * (SIN_POLY[4] + z * SIN_POLY[5]))))
        return x + z * x * r

    def pcos(a):
        TWO_PI = 2 * math.pi
        PIO2 = math.pi / 2
        x = a % TWO_PI
        if x < 0:
            x += TWO_PI
        quad = int(x / PIO2)
        t = x - quad * PIO2
        if t <= PIO2 * 0.5:
            c, s = kcos(t), ksin(t)
        else:
            u = PIO2 - t
            c, s = ksin(u), kcos(u)
        return [c, -s, -c, s][quad & 3]

    for _ in range(100000):
        a = random.uniform(-40, 40)
        maxe = max(maxe, abs(pcos(a) - math.cos(a)))
    print(f"wrote {out_path}  poly max|err| vs math.cos ~ {maxe:.3e}")


if __name__ == "__main__":
    main()
