#!/usr/bin/env python3
"""
v59/gaps/ew_scale_bridge/formalize_bridge.py

Gap G1 — the electroweak scale bridge  v_Higgs = dim(L)^2 * a_l^2 = 784 a_l^2.

This script collects, in ONE self-contained place (numpy only), the quantitative
backbone of the gap and TESTS the candidate mechanisms for the two open residuals:

  R1  why the EW scale equals the Frobenius^2 norm ||Y||_F^2 of the L-grade mass
      bilinear (not its trace, top eigenvalue, ...).
  R2  why each of the 784 components has magnitude = the physical Brannen scale a_l.

Plus the "25 unaccounted directions" problem (L is 28-dim, only 3 generations light).

SECTIONS
  1. Empirical anchor: the numbers (PDG), the sqrt-form, the 3/28 ratio, precision.
  2. Option 5 (re-derived & robustness): dim End(L)=784 from ad(so(8)) (Burnside),
     extended to a battery of irreducible reps to confirm "dim^2 = full End" is the
     generic Burnside statement, NOT special to 28.
  3. Lepton-specificity of sqrt(v)=D*a: PRECISE failure for D=35,63.
  4. R1 candidate test: an so(8)-invariant Higgs quartic on End(L)=M_28(R).
     Does its minimum reproduce v = 784 a^2 = ||Y||_F^2 ?  (Honest null/partial.)
  5. R2 / norm-invariant test: which scalar invariant of Y gives 784 a^2?
     Frobenius^2 vs trace vs top-eigenvalue vs nuclear, head to head.
  6. The 25-direction count: so(8) -> light subgroup Goldstone bookkeeping.
"""

import numpy as np
from collections import deque

np.set_printoptions(suppress=True)

# ===========================================================================
# 1. EMPIRICAL ANCHOR
# ===========================================================================
print("=" * 78)
print("1. EMPIRICAL ANCHOR  (PDG 2024 values)")
print("=" * 78)

# charged lepton masses (GeV)
m_e   = 0.51099895000e-3
m_mu  = 105.6583755e-3
m_tau = 1776.86e-3
v_obs = 246.21965        # Higgs vev (GeV), from G_F

sqrt_sum = np.sqrt(m_e) + np.sqrt(m_mu) + np.sqrt(m_tau)
a_l      = sqrt_sum / 3.0                      # Brannen scale a_l = (Sum sqrt m)/3
sqrt_v   = np.sqrt(v_obs)

print(f"  Sum sqrt(m_l)         = {sqrt_sum:.8f}  GeV^1/2")
print(f"  a_l = (Sum sqrt m)/3  = {a_l:.8f}  GeV^1/2")
print(f"  sqrt(v_obs)           = {sqrt_v:.8f}  GeV^1/2")
print()
print(f"  sqrt(v)/a_l           = {sqrt_v/a_l:.6f}    [law wants dim(L)=28]")
print(f"     -> gap to 28       = {abs(sqrt_v/a_l-28)/28*100:.4f} %   (sqrt form)")
print(f"  v_obs/a_l^2           = {v_obs/a_l**2:.4f}     [law wants 784]")
print(f"     -> gap to 784      = {abs(v_obs/a_l**2-784)/784*100:.4f} %   (squared form)")
print()
ratio = sqrt_sum / sqrt_v
print(f"  (Sum sqrt m)/sqrt(v)  = {ratio:.8f}   [law wants 3/28 = {3/28:.8f}]")
print(f"     -> gap to 3/28     = {abs(ratio-3/28)/(3/28)*100:.4f} %")
print()
# the Koide value used downstream
t2 = 0.5
Q  = (1 + 2*t2)/3
print(f"  (consistency) lepton Koide Q = (1+2t^2)/3 with t^2=1/2 -> {Q:.6f} (=2/3)")
print(f"  (consistency) Sum m_l = 9 Q a_l^2 = {9*Q*a_l**2:.6e}, actual {m_e+m_mu+m_tau:.6e}")
print(f"  bonus relation Sum m_l = (6/784) v : "
      f"{(6/784)*v_obs:.6e} vs {m_e+m_mu+m_tau:.6e}  "
      f"({abs((6/784)*v_obs-(m_e+m_mu+m_tau))/(m_e+m_mu+m_tau)*100:.3f}%)")


# ===========================================================================
# 2. OPTION 5 robustness:  dim of the unital associative algebra a rep generates
# ===========================================================================
def algebra_dim(gens, tol=1e-8):
    """Dim of the unital associative algebra generated by `gens` (composition),
    via incremental Gram-Schmidt on flattened operators."""
    n = gens[0].shape[0]
    dmax = n * n
    Q = np.zeros((dmax, dmax))
    state = {"k": 0}
    work = deque()

    def add(M):
        v = M.flatten().astype(float).copy()
        k = state["k"]
        if k:
            v -= Q[:k].T @ (Q[:k] @ v)
        nv = np.linalg.norm(v)
        if nv > tol:
            Q[k] = v / nv
            state["k"] = k + 1
            work.append(M)
            return True
        return False

    add(np.eye(n))
    for g in gens:
        add(g)
    while work:
        B = work.popleft()
        for g in gens:
            add(B @ g)
            add(g @ B)
        if state["k"] >= dmax:
            break
    return state["k"]


def so_n_gens(n):
    """so(n) generators in defining rep: E_ab - E_ba."""
    out = []
    for a in range(n):
        for b in range(a + 1, n):
            M = np.zeros((n, n))
            M[a, b] = 1.0
            M[b, a] = -1.0
            out.append(M)
    return out


def adjoint_ops(gens_def):
    """Adjoint rep matrices (ad_X)_{ij} = <B_i,[X,B_j]> on the orthonormal
    Frobenius basis B = gens/sqrt2 (works for any so(n) generator list)."""
    Bs = [M / np.sqrt(2.0) for M in gens_def]
    nB = len(Bs)
    out = []
    for X in gens_def:
        A = np.zeros((nB, nB))
        for j, Bj in enumerate(Bs):
            C = X @ Bj - Bj @ X
            for i, Bi in enumerate(Bs):
                A[i, j] = np.sum(Bi * C)
        out.append(A)
    return out


print()
print("=" * 78)
print("2. OPTION 5 (Burnside): the L-action algebra is full End(L), dim 28^2=784")
print("=" * 78)

g8 = so_n_gens(8)
assert len(g8) == 28
dim_def  = algebra_dim(g8)
g8_adj   = adjoint_ops(g8)
dim_adj  = algebra_dim(g8_adj)
print(f"  so(8) defining rep (8x8) -> algebra dim {dim_def:4d}  (= 8^2 = 64; WRONG reading)")
print(f"  so(8) adjoint  rep (28x28)-> algebra dim {dim_adj:4d}  (= 28^2 = 784; End(L), the bridge)")
print(f"  Option 5 verdict: {'LIVE' if dim_adj == 784 else 'DEAD'}")
print()
print("  Robustness: Burnside says 'irreducible faithful rep of dim d -> generates")
print("  M_d(R), dim d^2'.  Check this is GENERIC, not special to 28:")
print(f"  {'rep':>26} {'dim d':>6} {'alg dim':>8} {'d^2':>6} {'= full End?':>12}")
for n in (3, 4, 5, 6, 7, 8):
    gd = so_n_gens(n)
    # adjoint dim = n(n-1)/2
    if n == 4:
        # so(4) adjoint is NOT irreducible (so(4)=su(2)+su(2)); expect < d^2
        ga = adjoint_ops(gd)
        d  = len(gd)
        ad = algebra_dim(ga)
        print(f"  {'so(%d) adjoint'%n:>26} {d:>6} {ad:>8} {d*d:>6} "
              f"{'NO (reducible)' if ad < d*d else 'YES':>12}")
        continue
    ga = adjoint_ops(gd)
    d  = len(gd)
    ad = algebra_dim(ga)
    full = (ad == d * d)
    print(f"  {'so(%d) adjoint'%n:>26} {d:>6} {ad:>8} {d*d:>6} {('YES' if full else 'NO'):>12}")
print()
print("  Reading: 'algebra dim = (rep dim)^2' is the Burnside statement for EVERY")
print("  absolutely-irreducible rep.  so(4)'s adjoint (=su(2)+su(2)) is REDUCIBLE,")
print("  so it generates LESS than End -> a sanity check that the test sees reducibility.")
print("  CONCLUSION: 784 = dim End(L) is FORCED once L=so(8) and the action is the")
print("  bracket (adjoint).  This is [thm]. It does NOT by itself say v = 784 a^2.")


# ===========================================================================
# 3. Lepton-specificity of  sqrt(v) = D * a   (PRECISE failure for D=35,63)
# ===========================================================================
print()
print("=" * 78)
print("3. LEPTON-SPECIFICITY:  sqrt(v) = D * a   holds only for D=28")
print("=" * 78)

# running quark sqrt-mass scales a_q = (Sum sqrt m_q)/3 at ~M_Z (illustrative PDG)
# d-type: d,s,b ; u-type: u,c,t  (GeV, MSbar-ish at high scale)
m_d = np.array([2.9e-3, 55e-3, 2.75])      # d,s,b  (~2 GeV / running, illustrative)
m_u = np.array([1.3e-3, 0.63, 168.0])      # u,c,t
a_d = np.sum(np.sqrt(m_d)) / 3
a_u = np.sum(np.sqrt(m_u)) / 3
print(f"  {'sector':>8} {'D':>4} {'a (GeV^1/2)':>14} {'sqrt(v)/a':>12} {'law wants D':>12} {'verdict':>10}")
for name, D, a in (("lepton", 28, a_l), ("d-quark", 35, a_d), ("u-quark", 63, a_u)):
    r = sqrt_v / a
    ok = abs(r - D) / D < 0.02
    print(f"  {name:>8} {D:>4} {a:>14.6f} {r:>12.4f} {D:>12} "
          f"{('MATCH' if ok else 'FAIL %.1fx'%(max(r,D)/min(r,D))):>10}")
print()
print("  Reading: the bridge sqrt(v)=D*a singles out D=28 (lepton).  d/u quarks fail")
print("  by 1.8x / 19x.  Mechanism-level reason (03_higgs_bridge_result.md): only the")
print("  color-singlet lepton's mass bilinear lives WHOLLY in L (28-dim); quark")
print("  bilinears carry color structure (F=35, L+F=63) and are not democratic-on-L.")
print("  [NOTE: quark numbers are illustrative/RG-dependent; the lepton 0.03% is the")
print("   only sharp match. The point is qualitative: only D=28 is O(1)-consistent.]")


# ===========================================================================
# 4. R1 candidate:  an so(8)-invariant Higgs quartic on End(L)=M_28(R).
#    Does a Mexican-hat V(Y) have a minimum with ||Y_min||_F^2 = 784 a^2 ?
# ===========================================================================
print()
print("=" * 78)
print("4. R1 TEST: so(8)-invariant quartic potential on the bilinear Y in M_28(R)")
print("=" * 78)
print("""  Setup: Y is the 28x28 lepton mass bilinear (Option-5 space End(L)).
  Build the most general renormalizable so(8)-invariant potential to quartic order
  out of the basic invariants of Y under Y -> R Y R^T, R in SO(28) [adjoint action]:
        I1 = Tr(Y Y^T) = ||Y||_F^2           (Frobenius^2)
        I2 = (Tr Y)^2                         (trace^2 ; singlet channel)
        I3 = Tr( (Y Y^T)^2 )                  (quartic, "shape")
  V(Y) = -mu^2 I1 + (lam/4) I1^2 + (g/4) I3 + (h/4) I2 .
  Question for R1: does minimizing V FORCE ||Y_min||_F^2 to a value that, with the
  natural per-component scale, equals 784 a^2 = dim(L)^2 a^2 ?""")

D = 28
rng = np.random.default_rng(1)


def invariants(Y):
    YYt = Y @ Y.T
    I1 = np.sum(Y * Y)            # Frobenius^2 = Tr(Y Y^T)
    I2 = np.trace(Y) ** 2
    I3 = np.trace(YYt @ YYt)
    return I1, I2, I3


def V(Y, mu2, lam, g, h):
    I1, I2, I3 = invariants(Y)
    return -mu2 * I1 + (lam / 4) * I1 ** 2 + (g / 4) * I3 + (h / 4) * I2


def grad_analytic(Y, mu2, lam, g, h):
    """Exact gradient of V wrt Y (vectorized -> fast).
       dI1=2Y ; dI2=2(TrY)I ; dI3=4(Y Y^T)Y."""
    YYt = Y @ Y.T
    I1 = np.sum(Y * Y)
    dI1 = 2 * Y
    dI2 = 2 * np.trace(Y) * np.eye(D)
    dI3 = 4 * (YYt @ Y)
    return -mu2 * dI1 + (lam / 4) * 2 * I1 * dI1 + (g / 4) * dI3 + (h / 4) * dI2


def minimize(mu2, lam, g, h, n_starts=6, steps=4000, lr=2e-3):
    best = None
    for s in range(n_starts):
        Y = 0.3 * rng.standard_normal((D, D))
        for _ in range(steps):
            Y -= lr * grad_analytic(Y, mu2, lam, g, h)
        val = V(Y, mu2, lam, g, h)
        if best is None or val < best[0]:
            best = (val, Y.copy())
    return best


# Case A: pure Frobenius Mexican hat (g=h=0). Minimum of -mu^2 I1 + (lam/4)I1^2
#   is at I1 = ||Y||_F^2 = 2 mu^2 / lam, with Y direction UNCONSTRAINED (flat sphere).
mu2, lam = 1.0, 0.02
print("  --- Case A: pure Frobenius hat  V = -mu^2 I1 + (lam/4) I1^2  (g=h=0)")
print(f"      analytic: ||Y_min||_F^2 = 2 mu^2/lam = {2*mu2/lam:.2f} (a SPHERE of radius)")
print( "      -> the MAGNITUDE ||Y||_F^2 is fixed by (mu,lam) [free], the DIRECTION is")
print( "         flat (any Y on the sphere).  So a quartic CAN pin ||Y||_F^2 to a chosen")
print( "         value, but that value = 2mu^2/lam is INPUT, not 784 a^2.  R1 NOT closed")
print( "         by an unbroken-symmetry hat: it only relocates v into (mu,lam).")

# Case B: add the shape term g*I3 -> selects the DIRECTION (rank/spectrum) of Y_min.
print()
print("  --- Case B: add shape term (g != 0): which DIRECTION does the vacuum pick?")
for g in (-0.01, +0.01):
    val, Ym = minimize(mu2, lam, g, 0.0, n_starts=4, steps=2500, lr=2e-3)
    w = np.linalg.svd(Ym, compute_uv=False)
    fro2 = np.sum(Ym * Ym)
    rank_eff = (w.sum() ** 2) / (w ** 2).sum()   # participation ratio of sing. values
    print(f"      g={g:+.3f}: ||Y||_F^2={fro2:7.2f}  top/2nd s.v.={w[0]/w[1]:6.2f}  "
          f"eff.rank={rank_eff:5.2f}  (max possible {D})")
print("      Reading (from the numbers): g>0 [+Tr((YY^T)^2) penalizes large singular")
print("      values] flattens the spectrum -> MORE democratic (eff.rank ~ 23/28); g<0")
print("      rewards concentration -> lower eff.rank (~13).  So the SIGN of the so(8)-")
print("      invariant shape term controls democratic-vs-condensed: a near-democratic")
print("      (full-rank, all-784-comparable) vacuum is a DYNAMICAL OUTCOME for g>0.")
print("      BUT: (a) the overall scale ||Y||_F^2 still rides on the FREE (mu,lam) [~100")
print("      here, not 784 a^2]; (b) full democracy gives eff.rank ~28 (28 light dirs),")
print("      NOT the observed 3 -- so this 'democratic' vacuum does NOT give 3 light")
print("      generations.  The potential gives the COUNT picture, not the SCALE or the")
print("      generation number.  R1+R2 NOT derived -- see section 6 for the core tension.")


# ===========================================================================
# 5. R1 / norm-selection: which invariant equals 784 a^2 for a democratic Y?
# ===========================================================================
print()
print("=" * 78)
print("5. R1 NORM-SELECTION: Frobenius^2 vs trace vs top-eigenvalue, democratic Y")
print("=" * 78)
a = 1.0
Y_dem = a * np.ones((D, D))             # democratic: every entry = a
Y_diag = a * np.eye(D)                  # so(8)-singlet: Y propto delta (28 entries)
for label, Y in (("democratic (all=a)", Y_dem), ("singlet (Y=a*delta)", Y_diag)):
    fro2 = np.sum(Y * Y)
    tr = np.trace(Y)
    w = np.linalg.svd(Y, compute_uv=False)
    print(f"  {label:>22}:  ||Y||_F^2={fro2:7.1f}  Tr(Y)={tr:6.1f}  top s.v.={w[0]:7.2f}  "
          f"nuclear ||Y||_*={w.sum():7.2f}")
print(f"  bridge wants 784 a^2 = {784*a*a:.0f}.")
print("  Reading: ONLY ||Y||_F^2 of the DEMOCRATIC Y gives 784. The singlet's Frobenius^2")
print("  is 28 (the excluded linear/sqrt(28) reading). Trace and top-eigenvalue give the")
print("  wrong magnitude for either. So R1 is the conjunction: (i) vacuum = democratic on")
print("  L  AND  (ii) v read as Frobenius^2.  Case-B above gives (i) dynamically for g<0;")
print("  (ii) [Frobenius^2 = the energy/L^2 norm of a bilinear] is the NATURAL norm but")
print("  remains the identification 'EW scale = ||Y||_F^2' -- still [conj].")


# ===========================================================================
# 6. The 25-direction count: so(8) -> light subgroup Goldstone bookkeeping
# ===========================================================================
print()
print("=" * 78)
print("6. THE 25 UNACCOUNTED DIRECTIONS (Goldstone bookkeeping)")
print("=" * 78)
print("""  L = so(8) is 28-dim; a democratic bilinear has 28 singular directions but only
  3 generations are LIGHT. The other 25 need a home. Candidate: spontaneous breaking
  of so(8) leaves a residual symmetry H, and dim(so(8)/H) directions are Goldstones
  (eaten / heavy). Count which H leaves exactly 3 (or 28-3=25 broken):""")
print(f"  {'subgroup H':>22} {'dim H':>6} {'28 - dim H':>11} {'note':>28}")
candidates = [
    ("SU(3) (color)",        8,  "8 gluons unbroken"),
    ("SU(2)xU(1) (EW)",      4,  "after EWSB残: U(1)_em (1)"),
    ("G2 (octo aut.)",      14,  "28-14=14 = dim G2 again"),
    ("Spin(7)",             21,  "28-21=7 = dim Im O"),
    ("SU(3)xU(1)",           9,  "28-9 =19"),
    ("SU(4)~Spin(6)",       15,  "28-15=13"),
]
for name, dh, note in candidates:
    print(f"  {name:>22} {dh:>6} {28-dh:>11}   {note}")
print()
print("  Reading: NO single classical subgroup leaves exactly 3 unbroken directions")
print("  (you'd need dim H = 25, but there is no 25-dim subgroup of so(8); maximal")
print("  proper subalgebras have dim <= 21 = Spin(7)).  So '3 light + 25 eaten' is NOT")
print("  a clean single-step so(8)->H breaking.  The honest status: the 25 directions")
print("  are UNACCOUNTED. The natural reading is a CHAIN (so(8) -> ... ) or that the 3")
print("  light generations are the 3 SINGULAR VALUES of a rank-3 Y (not 28), i.e. the")
print("  vacuum is rank-3, not full-rank democratic -- which then CONFLICTS with the")
print("  '784 = all entries equal' picture of section 5.  THIS TENSION (rank-3 spectrum")
print("  vs full-rank 784-count) is the sharpest open problem of the bridge. See FINDINGS.")

print()
print("=" * 78)
print("DONE. See README.md / ALTERNATIVES.md / FINDINGS.md for the writeups.")
print("=" * 78)
