#!/usr/bin/env python3
# species_enum.py — enumerate closure-allowed charged cycles: the discrete
# species skeleton. Subordinate to CHARGE.md §8.6.
#
# A cycle = ring of N edges, each edge an interval lock p:q from the comb
# (Tenney height <= 6, i.e. comb_limit=6: admits 3:1, 3:2, 2:1 and inverses).
#   closure:    prod(p_l) = prod(q_l)                       (frequency closure)
#   charge grp: the branch of edge l enters the monodromy with coefficient
#               prod(p_{>l}) / prod(q_{>=l})   (charge_sym.mac PART 2)
#               -> the branch subgroup is generated by those rationals;
#                  its index Q gives the charge quantum 1/Q  (Z_Q)
#
# 2026-08-02 REVISION — one defect repaired, one claim retracted:
#
#  (D8) THE ENUMERATION WAS INCOMPLETE BY 99%. It used
#       combinations_with_replacement, i.e. sorted MULTISETS of edges, so
#       only one cyclic ORDERING of each edge multiset was ever generated.
#       But Q depends on the order: the file's own canon() docstring says
#       so, and the very example it cites -- (1/1, 2/3, 3/2), which is Z_2
#       -- was never generated, because only the sorted (1/1, 3/2, 2/3)
#       (which is Z_3) survives that filter. Shipped census: 175 classes.
#       True census over ordered cycles: 17922. N=4 alone went from
#       {Q=1:4, 2:2, 3:5, 4:1} to {Q=1:15, 2:11, 3:9, 4:1, 6:1} -- a whole
#       Q=6 class was invisible. FIX: product() over ordered cycles.
#       (The structural conclusion survives: every quantum is still
#       1/(2^a 3^b), the full Q set just gains 24, 36, 54.)
#
#  (D9) NO SIZE FILTER AND NO MASS TABLE ARE EMITTED ANY MORE. The old
#       version applied N >= k*xi with xi = 4 and printed
#       M(N,Q,k) = N*e_bal + k*CORE/Q. Both parts were unsound:
#         - xi = 4 was the FWHM of a step profile on a UNISON FK chain,
#           not a property of an interval cycle, and not the continuum
#           width sqrt(2A/V'')=0.71 either (charge_fk.c section 4 note).
#           The measured floor is N/k >= 6 on a unison FK ring; carrying
#           that number onto interval cycles of 3-8 voices is unjustified.
#         - the core term linear in k/Q assumed the 1/Q scaling of
#           CHARGE §7.2, whose only "measurement" was the unison-ring
#           artifact retracted in charge_fk.c section 6.
#       What remains sound is the CLOSURE + HOLONOMY census, which is
#       exact arithmetic on the fabric's own locks. That is what this
#       file now emits, and nothing more.

from fractions import Fraction
from itertools import product
from math import gcd
from collections import Counter

COMB = [(1, 1), (2, 1), (1, 2), (3, 1), (1, 3), (3, 2), (2, 3)]
NMAX = 8


def lcm(a, b):
    return a * b // gcd(a, b)


def branch_coeffs(edges):
    """the rational coefficient each edge's branch integer contributes to
    the monodromy offset: prod(p_{>l}) / prod(q_{>=l})."""
    N = len(edges)
    out = []
    for l in range(N):
        num, den = 1, edges[l][1]
        for j in range(l + 1, N):
            num *= edges[j][0]
            den *= edges[j][1]
        out.append(Fraction(num, den))
    return out


def charge_group(edges):
    """Q = index of the subgroup of Q generated by the branch coefficients.
    The generator is their gcd; Q = 1/gcd. (On this comb the gcd always has
    numerator 1, so Q = lcm of denominators too -- verified over all 17922
    classes -- but the gcd is the definition and is what is computed.)"""
    g = Fraction(0)
    for r in branch_coeffs(edges):
        if g == 0:
            g = r
        else:
            g = Fraction(gcd(g.numerator * r.denominator, r.numerator * g.denominator),
                         g.denominator * r.denominator)
    return (1 / g).numerator if g != 0 else 1


def closure_ok(edges):
    pp = qq = 1
    for p, q in edges:
        pp *= p
        qq *= q
    return pp == qq


def canon(edges):
    """canonical form up to rotation and traversal reversal. Reversing
    traversal inverts each edge map: (p,q) -> (q,p). A plain reversal
    WITHOUT the swap is NOT a symmetry -- (1/1,3/2,2/3) [pitches 3:2:3,
    Z_3] and (1/1,2/3,3/2) [pitches 2:2:3, Z_2] are distinct cycles."""
    N = len(edges)
    forms = []
    for e in (tuple(edges), tuple((q, p) for p, q in reversed(edges))):
        for r in range(N):
            forms.append(e[r:] + e[:r])
    return min(forms)


rows = {}
for N in range(2, NMAX + 1):
    for combo in product(COMB, repeat=N):          # ORDERED cycles (D8)
        if not closure_ok(combo):
            continue
        c = canon(combo)
        if c in rows:
            continue
        rows[c] = (N, charge_group(c))

print(f"# species_enum — closure-allowed cycles over the comb {COMB}")
print(f"# ordered cycles, N = 2..{NMAX}, canonical up to rotation + traversal reversal")
print(f"# distinct cycles (dihedral classes): {len(rows)}\n")

byNQ = Counter()
byQ = Counter()
rep = {}
for c, (N, Q) in rows.items():
    byNQ[(N, Q)] += 1
    byQ[Q] += 1
    rep.setdefault((N, Q), c)

print(f"{'N':>2} {'Q':>3} {'quantum':>8} {'classes':>8}  cycle (one representative)")
for (N, Q) in sorted(byNQ):
    s = ':'.join(f"{p}/{q}" for p, q in rep[(N, Q)])
    print(f"{N:>2} {Q:>3} {f'1/{Q}':>8} {byNQ[(N, Q)]:>8}  {s}")

print("\n# --- charge quanta present ---")
for Q in sorted(byQ):
    fac = []
    m = Q
    for pr in (2, 3, 5, 7):
        e = 0
        while m % pr == 0:
            m //= pr
            e += 1
        if e:
            fac.append(f"{pr}^{e}")
    print(f"#   Q={Q:>3}  ({'*'.join(fac) if fac else '1'})   {byQ[Q]:>5} classes")

def only_2_3(q):
    for pr in (2, 3):
        while q % pr == 0:
            q //= pr
    return q == 1


assert all(only_2_3(Q) for Q in byQ), "a quantum with a prime factor outside {2,3} appeared"

print("\n# reading:")
print("# Every charge quantum is 1/(2^a * 3^b) -- the comb carries only the")
print("# primes 2 and 3 (Tenney <= 6), so no fifth-of-charge exists at")
print("# comb_limit=6. The small quantum numbers ARE the small harmonic")
print("# numbers: structural, not fitted. This is the one claim this file")
print("# supports on its own.")
print("#")
print("# Q=1 cycles carry integer holonomy only (unison-equivalent).")
print("# Q=2 carries the octave/spinor class; Q=3 the thirds (quark pattern);")
print("# Q=6,12,... carry both.")
print("#")
print("# NOT claimed here (see D9 in the header): any size floor, any mass")
print("# table, any proton/neutron slot assignment. Those need (i) the 1/Q")
print("# core scaling measured on a Z_Q interval chain, (ii) e_balance from")
print("# the MASS program, (iii) E_dress from EM5, and (iv) the geometric")
print("# closure filter (link-length band), none of which exist yet.")
